- name: Install Dependencies
    run: make install-dev
- name: Run Tests
    run: make coverage
- name: SonarCloud Scan
    uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}