id: ecr
  uses: aws-actions/configure-aws-credentials@v1
  with:
    access_key: ${{ secrets.AWS_ACCESS_KEY }}
    secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    region: ${{ secrets.AWS_REGION }}